spring:
  application:
      name: shoppal-provider
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/snow
      username: root
      password: snow
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

  redis:
    database: 0
    host: localhost
    port: 6379
    password:
  pool:
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0
  timeout: 0
dubbo:
  scan:
      base-packages: com.shoppal.service.impl
  registry:
    address: zookeeper://localhost:2181

mybatis:
  typeAliasesPackage: com.shoppal.model.*
  mapperLocations: classpath:mapper/*.xml